services:
  ironpaste:
    build: .
    #ports:
      #- "5005:5005" # to expose on your host
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=0
      - FLASK_CONFIG=production
      - DATABASE_URL=sqlite:////app/instance/prod.db
    command: >
      sh -c "mkdir -p instance &&
             if [ ! -d 'migrations' ]; then flask db init; fi &&
             flask db migrate -m 'Initial migration' || true &&
             flask db upgrade &&
             gunicorn --bind 0.0.0.0:5005 app:app"